config/routes.rb
LsAtomic::Application.routes.draw do 

  resources :notes
  resources :events

  resources :user_sessions
  resources :users do
    member do
      get :courses
    end
  end

  resources :courses do
    resources :lessons
    resources :quizzes
    resources :components
    member do
      get :users
      get :success_stats
      get :cards_due_stats
      get :course_achieved_stats
      get :student_status
    end
    resources :study, :only => [:index, :show]
    resources :memories, :only => [:index, :update] 
  end

  resources :components 

  resources :videos, :only => [:create, :update, :destroy, :edit]
  resources :enrollments, :only => [:create, :update, :destroy]

  resources :memories
  resources :quizzes
  resources :responses, :only => [:create, :update, :edit, :index, :show]

  resources :lessons do
    resources :events
  end

  resources :lesson_statuses
  resources :authentications

  match '/auth/:provider/callback' => 'authentications#create'

  match '/signup', :to => 'users#new'
  match '/signin', :to => 'user_sessions#new'
  match '/signout', :to => 'user_sessions#destroy'
  match '/about', :to => 'pages#about'
  match '/contact', :to => 'pages#contact'
  match '/help', :to => 'pages#help'
  match '/home', :to => 'pages#home'
   
  root :to => 'pages#welcome'

  resources :lesson_components, :only => [:update, :create, :destroy]

  match "/quizzes/challenge_link", :to => "quizzes#challenge_link"

end

app/models/video.rb
class Video < ActiveRecord::Base
  attr_accessible :name, :url, :start_time, :end_time, :component_id, :description

  belongs_to :component
  belongs_to :step

  validates :url, :presence => true
  
end

app/helpers/videos_helper.rb
module VideosHelper


  def video_link(video)
    videoID = get_youtube_id(video.url, 'v')
    name = video.name || "Watch"
    link_to name, "#", :class => "color-box-link", 
                       'data-url' => videoID, 
                       'data-start-time' => video.start_time,
                       'data-end-time' => video.end_time
  end

  def get_youtube_id(url, name)
    urlparts = url.split('?')
    if(urlparts.length > 1)
      parameters = urlparts[1].split('&')
      parameters.each { |param|
        paramparts = param.split('=')
        if ((paramparts.length > 1) && (CGI.unescape(paramparts[0]) == name))
         return CGI.unescape(paramparts[1])
        end
      }
    end
    return nil
  end
end

app/views/videos/_video.html.erb
<div id="video-area">
  <div class="video-name"> <%= video.name %> |
  <% if edit == true %>
    <%= link_to "Edit", edit_video_path(video.id) %> | <%= link_to "Delete", video_path(video), :method => :delete %>
  <% else %>
    <a href="#">Play</a></div>
  <% end %>
  <p> <%= video.description %></p>
  <div id="video-parameters" class="hidden">
    <div id="video-embed-url"><%= video.url %></div>
    <div id="video-start-time"><%= video.start_time %></div>
    <div id="video-end-time"><%= video.end_time %></div>
  </div>
</div>

app/views/videos/edit.html.erb
<%= form_for(@video) do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
    <%= f.hidden_field :component_id, :value => @component.id %>
  </div>
  <div class="field">
    <%= f.label :start_time %><br />
    <%= f.text_field :start_time %>
  </div>
  <div class="field">
    <%= f.label :end_time %><br />
    <%= f.text_field :end_time %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
   <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
 
  <div class="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>