config/routes.rb
LsAtomic::Application.routes.draw do 

  resources :notes
  resources :events

  resources :user_sessions
  resources :users do
    member do
      get :courses
    end
  end

  resources :courses do
    resources :lessons
    resources :quizzes
    resources :components
    member do
      get :users
      get :success_stats
      get :cards_due_stats
      get :course_achieved_stats
      get :student_status
    end
    resources :study, :only => [:index, :show]
    resources :memories, :only => [:index, :update] 
  end

  resources :components 

  resources :videos, :only => [:create, :update, :destroy, :edit]
  resources :enrollments, :only => [:create, :update, :destroy]

  resources :memories
  resources :quizzes
  resources :responses, :only => [:create, :update, :edit, :index, :show]

  resources :lessons do
    resources :events
  end

  resources :lesson_statuses
  resources :authentications

  match '/auth/:provider/callback' => 'authentications#create'

  match '/signup', :to => 'users#new'
  match '/signin', :to => 'user_sessions#new'
  match '/signout', :to => 'user_sessions#destroy'
  match '/about', :to => 'pages#about'
  match '/contact', :to => 'pages#contact'
  match '/help', :to => 'pages#help'
  match '/home', :to => 'pages#home'
   
  root :to => 'pages#welcome'

  resources :lesson_components, :only => [:update, :create, :destroy]

  match "/quizzes/challenge_link", :to => "quizzes#challenge_link"

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :playable, :polymorphic => true
  belongs_to :lesson

  validates :lesson_id, :presence => true

  default_scope :order => 'order_number'

  before_create :assign_order_number

  def assign_order_number
    self.order_number = lesson.events.count
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  before_filter :authenticate

  def index
    @lesson = Lesson.find(params[:lesson_id])
    @events = @lesson.events.includes(:playable).all

    events_json = []

    @events.each do |event|
      event_json = {}
      event_json["type"] = event.playable_type
      event_json["id"] = event.playable_id
      event_json["event_id"] = event.id
      
      if event.playable_type == "Note"
        event_json["pause"] = false
        event_json["content"] = event.playable.content
        if event.playable.is_document
          event_json["type"] = "Document"
        end
      else
        event_json["pause"] = true
      end

      event_json["video_url"] = event.video_url
      event_json["start_time"] = event.start_time
      event_json["end_time"] = event.end_time
      
      events_json << event_json
    end

    current_event = @lesson.lesson_statuses.find_by_user_id(current_user).event_id

    respond_to do |format|
      format.json { render :json => {:events => events_json, :current_event => current_event}}
      format.html   { render :partial => "event", :collection => @events, :as => :event, :layout => false }
    end
  end

  def authorized_teacher
    @course = Course.find(params[:course_id]) if params[:course_id]
    if current_user.perm != "admin" and !current_user.teacher?(@course)
      redirect_to root_path
    end
  end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.html.erb
<div id="<%= event.playable_type.downcase %>-<%= event.playable.id %>" title="Time: <%= event.start_time %> s" class="event <%= event.playable_type.downcase  %>">
  <div class="hidden data" id="event-<%= event.id %>"
    data-id="<%= event.playable.id %>"
    data-video="<%= event.video_url %>"
    data-start_time="<%= event.start_time %>"
    data-end_time="<%= event.end_time %>"
    data-playable_type="<%= event.playable_type %>"
    data-order_number="<%= event.order_number %>"> </div>
  <% if event.playable_type == "Note" %>
    <div class="content markdown"><%=event.playable.content%></div>
    <% if current_user.can_edit?(event.lesson.course) %>
      <%= link_to "Edit", edit_note_path(event.playable_id), :remote => true %>
    <% end %>
  <% else %>
    <div class="question"><%=event.playable.question%></div>
    <% if current_user.can_edit?(event.lesson.course) %>
      <%= link_to "Edit", edit_course_quiz_path(event.lesson.course, event.playable_id), :remote => true %>
    <% end %>
  <% end %>
</div>

app/views/events/_form.html.erb
<% new_or_existing = event.new_record? ? 'new' : 'existing' %>
<% prefix = "#{parent_type}[#{new_or_existing}_event_attributes]" %>

<%= fields_for prefix, event do |event_form| %>
<table>
  <tr>
    <div class="field">
      <td><%= event_form.label :start_time, "Start time: " %></td>
      <td><%= event_form.text_field :start_time, :class => 'start_time' %></td>
      <td><a href="#" class="start-sync">Sync start</a></td>
    </div>
  </tr>
  <tr>
    <div class="field">
      <td><%= event_form.label :end_time, "End time: " %></td>
      <td><%= event_form.text_field :end_time, :class => 'end_time' %></td>
        <td><a href="#" class="end-sync">Sync end</a></td>
    </div>
  </tr>
</table>
<div class="current_video_url"></div>
<%= event_form.hidden_field :video_url %>
<%= event_form.hidden_field :lesson_id %>
<% end %>

app/views/events/create.html.erb
<h1>Events#create</h1>
<p>Find me in app/views/events/create.html.erb</p>

app/views/events/new.html.erb
<h1>Events#new</h1>
<p>Find me in app/views/events/new.html.erb</p>