config/routes.rb
LsAtomic::Application.routes.draw do 

  resources :notes
  resources :events

  resources :user_sessions
  resources :users do
    member do
      get :courses
    end
  end

  resources :courses do
    resources :lessons
    resources :quizzes
    resources :components
    member do
      get :users
      get :success_stats
      get :cards_due_stats
      get :course_achieved_stats
      get :student_status
    end
    resources :study, :only => [:index, :show]
    resources :memories, :only => [:index, :update] 
  end

  resources :components 

  resources :videos, :only => [:create, :update, :destroy, :edit]
  resources :enrollments, :only => [:create, :update, :destroy]

  resources :memories
  resources :quizzes
  resources :responses, :only => [:create, :update, :edit, :index, :show]

  resources :lessons do
    resources :events
  end

  resources :lesson_statuses
  resources :authentications

  match '/auth/:provider/callback' => 'authentications#create'

  match '/signup', :to => 'users#new'
  match '/signin', :to => 'user_sessions#new'
  match '/signout', :to => 'user_sessions#destroy'
  match '/about', :to => 'pages#about'
  match '/contact', :to => 'pages#contact'
  match '/help', :to => 'pages#help'
  match '/home', :to => 'pages#home'
   
  root :to => 'pages#welcome'

  resources :lesson_components, :only => [:update, :create, :destroy]

  match "/quizzes/challenge_link", :to => "quizzes#challenge_link"

end

app/models/lesson.rb
class Lesson < ActiveRecord::Base

  attr_reader :component_tokens

  has_many :events, :dependent => :destroy
  has_many :quizzes, :through => :events, 
                     :source => :playable,
                     :source_type => "Quiz"
  has_many :lesson_statuses, :dependent => :destroy
  has_many :lesson_components, :dependent => :destroy
  has_many :components, :through => :lesson_components
  belongs_to :course
  default_scope :order => 'lessons.order_number'
  validates :name, :uniqueness => { :scope => :course_id }

  after_create :create_lesson_statuses

  scope :incomplete_for, lambda {|user_id| joins(:lesson_statuses).merge(LessonStatus.where(:user_id => user_id, :completed => false)) }

  def next_lesson
    self.course.lessons.where("order_number > ?", self.order_number).first
  end



  def component_tokens=(ids)
    self.component_ids = ids.split(",")
  end

  private 

  def create_lesson_statuses
    course.students.each do |student|
      LessonStatus.create!(:user_id => student.id, :lesson_id => self.id)
    end
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  layout :choose_layout

  before_filter :grab_course_from_course_id 
  before_filter :authenticate
  before_filter :authorized_teacher, :except => :show 
  before_filter :select_lessons
  before_filter :enrolled, :only => :show

  def index
    @lessons = @course.lessons
  end

  def show
    @lesson = Lesson.find(params[:id])
    @status = @lesson.lesson_statuses.find_by_user_id(current_user)

    @lesson.components.each do |cmp|
      mem = current_user.memories.find_by_component_id(cmp)
      if not mem.viewed?
        mem.unlock!
      end
    end
  end

  def new
    @lesson = Lesson.new
  end

  def create
    @lesson = @course.lessons.build(params[:lesson])

    if @lesson.save
      flash[:success] = "Lesson created!"
      redirect_to edit_course_lesson_path(@course, @lesson)
    else
      render 'new'
    end
  end

  def edit
    @lesson = @course.lessons.find(params[:id])
    #@events = @lesson.events
    @note = Note.new
    @quiz = Quiz.new
  end

  def update
    @lesson = Lesson.find(params[:id])

    if @lesson.update_attributes(params[:lesson])
      flash[:success] = "Lesson updated!"
      redirect_to course_lessons_path(@course)
    else
      @note = Note.new
      @quiz = Quiz.new
      @events = @lesson.events
      render 'edit'
    end
  end

  def destroy
    @lesson = Lesson.find(params[:id])
    @lesson.destroy
  end
  
  private

  def grab_course_from_course_id
    @course = Course.find(params[:course_id]) if params[:course_id]
  end

  def choose_layout 
    if [ 'show' ].include? action_name
      'application'
    else
      'teacher'
    end
  end
  
  def authorized_teacher
    if current_user.perm != "admin" and !current_user.teacher?(@course)
      redirect_to root_path
    end
  end

  def select_lessons
    @lessons_selected = "selected"
  end

  def enrolled
    if not current_user.enrolled?(@course)
      flash[:error] = "You must be enrolled in the course to do watch lessons!"
      redirect_to root_path
    elsif current_user.teacher?(@course)
      flash[:error] = "You are a teacher in this course. You must be a student to watch lessons."
      redirect_to course_path(@course)
    end
  end

end

app/helpers/lessons_helper.rb
module LessonsHelper
  def fitName(lesson)
    name = lesson.name
    if (name.length > 20)
      name = name[0..17] + "..."
    end
    name
  end
end

app/views/lessons/_content.html.erb
    <div id="content"></div>

app/views/lessons/_form.html.erb
<%= form_for [@course, @lesson] do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/lessons/_lesson.html.erb
<li><%= lesson.name %> | <%= link_to "Edit", edit_course_lesson_path(lesson.course, lesson) %></li>

app/views/lessons/create.html.erb
<h1>Lessons#create</h1>
<p>Find me in app/views/lessons/create.html.erb</p>

app/views/lessons/destroy.html.erb
<h1>Lessons#destroy</h1>
<p>Find me in app/views/lessons/destroy.html.erb</p>

app/views/lessons/edit.html.erb
<% content_for :javascript do %>
  <%= javascript_include_tag "raphael-min" %>
  <%= javascript_include_tag "AddRemoveFields" %>
  <%= javascript_include_tag "LessonEdit" %>
<% end %>

<% breadcrumb :edit_lesson, @lesson %>

<div id="course_id" class="hidden"><%= @course.id %></div>
<div id="lesson_id" class="hidden"><%= @lesson.id %></div>
<div id="lesson-edit">
  
  <div id="video-area">
    <div id="vid-container">
      <div id="video-player"></div>
      <div id="video-url-div">
        <span id="url-label">YouTube URL:</span><input type ="text" id = "load_video_url" /><a href="#" id="load-video">Load video</a>
      </div>
    </div>
  </div>

  <div id="events-area-teacher" class="events-area">
    <%= render @lesson.events %> 
  </div>
  <div id="tabs-container">
    <div id="lesson-edit-tabs">
      <ul>
        <li><a href="#add-note">Add Note</a></li>
        <li><a href="#add-quiz">Add Quiz</a></li>
        <li><a href="#edit-components">Components</a></li>
      </ul>
      <div id="add-note">
        <%= render :partial => 'notes/form' %> 
      </div>

      <div id="add-quiz">
        <%= render :partial => 'quizzes/form' %>
      </div>

      <div id="edit-components">
        <%= render :partial => 'lesson_components/form' %>
        <ul id="component-list">
          <% @lesson.components.each do |comp| %>
            <% lc = comp.lesson_components.find_by_lesson_id(@lesson) %>
            <li id="lc-<%= lc.id %>"><%= link_to comp.name, course_component_path(@lesson.course,comp) %>
            <%= render :partial => 'lesson_components/remove', :locals => {:lc => lc } %>
            </li>
          <% end %>
        </ul>
    </div>
  </div>
</div>

app/views/lessons/index.html.erb
<% breadcrumb :lessons, @course %>

<%= link_to "Add a new lesson", new_course_lesson_path(@course), :class => 'add-course-item' %><br /><br />

<% if @lessons.empty? %>
  This course has no lessons yet!
<% else %>
  <%= render @lessons %>
<% end %>

app/views/lessons/new.html.erb
<% breadcrumb :new_lesson, @course %>
<%= render 'form' %>

app/views/lessons/show.html.erb
<% content_for :javascript do%>
  <%= javascript_include_tag "WatchLesson" %>
  <%= javascript_include_tag "raphael-min" %>
  <%= javascript_include_tag "Quiz" %>
<% end %>

<% if current_user.can_edit?(@course) %>
  <% breadcrumb :lesson, @lesson %>
<% else %>
  <% breadcrumb :lesson_student, @lesson %>
<% end %>

<h1 id="lesson-name"><%= @lesson.name %></h1>
<div id="lesson-area">

  <div id="video-area">
    <div id="player"></div>
  </div>
  <div id="stream-area">
    <div id="content"></div>
    <div id="control-links">
      <a id="resume" href="#" class="hidden">Resume</a>
      <a id="nextlink" href="#">Next</a>
      <a id="showall" href="#">Show all</a>
    </div>
  </div>
</div>
<div id ="document-area">
</div>

<div id="lesson-id" class="hidden"><%= @lesson.id %></div>
<div id="lesson-status-id" class="hidden"><%= @lesson.lesson_statuses.find_by_user_id(current_user).id %></div>
<div id="course-id" class="hidden"><%= @course.id %></div>

<div id="watch-lesson-links"><%= link_to "Study this course", course_study_index_path(@course), :class => "round quizbutton" %>
  <% if @lesson.next_lesson  %>
    <%= link_to "Next lesson", course_lesson_path(@course, @lesson.next_lesson), :class => "round quizbutton" %>
  <% end %>
</div>

app/views/lessons/update.html.erb
<h1>Lessons#update</h1>
<p>Find me in app/views/lessons/update.html.erb</p>