config/routes.rb
LsAtomic::Application.routes.draw do 

  resources :notes
  resources :events

  resources :user_sessions
  resources :users do
    member do
      get :courses
    end
  end

  resources :courses do
    resources :lessons
    resources :quizzes
    resources :components
    member do
      get :users
      get :success_stats
      get :cards_due_stats
      get :course_achieved_stats
      get :student_status
    end
    resources :study, :only => [:index, :show]
    resources :memories, :only => [:index, :update] 
  end

  resources :components 

  resources :videos, :only => [:create, :update, :destroy, :edit]
  resources :enrollments, :only => [:create, :update, :destroy]

  resources :memories
  resources :quizzes
  resources :responses, :only => [:create, :update, :edit, :index, :show]

  resources :lessons do
    resources :events
  end

  resources :lesson_statuses
  resources :authentications

  match '/auth/:provider/callback' => 'authentications#create'

  match '/signup', :to => 'users#new'
  match '/signin', :to => 'user_sessions#new'
  match '/signout', :to => 'user_sessions#destroy'
  match '/about', :to => 'pages#about'
  match '/contact', :to => 'pages#contact'
  match '/help', :to => 'pages#help'
  match '/home', :to => 'pages#home'
   
  root :to => 'pages#welcome'

  resources :lesson_components, :only => [:update, :create, :destroy]

  match "/quizzes/challenge_link", :to => "quizzes#challenge_link"

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

  before_filter :authenticate
  before_filter :authorized_user, :only => [:new, :create]
  before_filter :authorized_teacher, :only => [:student_status]

  layout :choose_layout

  def new
    @course = Course.new
    @title = "New Course"
  end

  def show
    @course = Course.find(params[:id])
    
    if current_user.can_edit?(@course)
      redirect_to student_status_course_path(@course)
      return 
    end

    @lessons = @course.lessons.all()
    @lesson_statuses = current_user.lesson_statuses.includes(:lesson).joins(:lesson).merge(Lesson.where(:course_id => @course))
    @components = @course.components
  end

  def create
    @course = Course.new(params[:course])
    if @course.save
      current_user.enroll_as_teacher!(@course)
      if(params[:course][:document].nil?)
        flash[:success] = "New course created!"
        redirect_to @course 
        return
      end
    else
      @title = "New Course"
      render 'new'
      return
    end

    result = @course.populate_with_tex(params[:course][:document])
    if result[:success]
      flash[:success] = "Course created and problems/components added!"
      redirect_to @course
    else
      document = params[:course][:document]
      result[:problems_added].each { |problem|
        document.gsub!("\\begin{problem}" + problem.first + "\\end{problem}", "")
      }
      @course.document = document
      @latex_on = true;
      render 'edit', :document => params[:course][:document]
    end

  end

  def edit
    @course = Course.find(params[:id])
  end

  def update
    @course = Course.find(params[:id])
    @latex_on = false

    if(@course.update_attributes(params[:course]))
      flash[:success] = "Course info saved!"
      if(params[:course][:document].nil?)
        redirect_to course_problems_path(@course)
      end
    else
      @course.document = params[:course][:document]
      @latex_on = true
      render 'edit'
      return
    end

    result = @course.populate_with_tex(params[:course][:document])
    if result[:success]
      flash[:success] = "Problems and Components added!"
      redirect_to course_problems_path(@course)
    else
      document = params[:course][:document]
      result[:problems_added].each { |problem|
        document.gsub!("\\begin{problem}" + problem.first + "\\end{problem}", "")
      }
      @course.document = document
      @latex_on = true;
      render 'edit', :document => params[:course][:document]
    end
  end

  def index
    @courses = Course.all
  end

  def users
    @title = "Users"
    @course = Course.find(params[:id])
    @teachers = @course.teachers
    @students = @course.students.paginate(:page => params[:page])
    render 'show_users'
  end

  def success_stats 
    @course = Course.find(params[:id])
    total_output = []
    correct_output = []
    ratings = current_user.memory_ratings.ratings_after(DateTime.now.utc - 28.days).in_course(@course)

    (0..28).each do |i| 
      correct_output << [i, 0]
      total_output << [i, 0]
    end

    ratings.each do |rating|
      day = 28 - ((Time.now.utc - rating.created_at)/60/60/24).round
      if rating.quality != 0
        correct_output[day] = [day, correct_output[day][1] + 1]
      end
      total_output[day] = [day, total_output[day][1] + 1]
    end
    output_json = { :success_stats => [ 
      {label: "Missed", 
       lines: {fill: true, fillColor: "rgba(255,0,0,0.8)"}, 
       data: total_output},
      {label: "Correct", 
       lines: {fill: true, fillColor: "rgba(0,255,0,0.8)"}, 
       data: correct_output}] }
    respond_to do |format|
      format.json { render :json => output_json.to_json }
    end
  end

  def cards_due_stats
    @course = Course.find(params[:id])     
    output = []
    (0..21).each{ |i|
      cards_due_day = current_user.memories.in_course(@course).due_before(Time.now.utc + i.day)
      output << [i, cards_due_day.count]
    }
    output_json = { :cards_due_stats => [output] }
    respond_to do |format|
      format.json { render :json => output_json.to_json }
    end
  end

  def course_achieved_stats
    @course = Course.find(params[:id])
    output = []
    first_rating = current_user.memory_ratings.in_course(@course).first
    diff = (Date.today - first_rating.created_at.to_date).to_i
    (0..diff).each{ |i|
      output << [i, 0]
    }

    current_user.memories.in_course(@course).includes(:memory_ratings).each{ | memory|
      ignore_below = 0 
      memory.memory_ratings.each { |rating|
        interval = rating.interval.floor
        index  = (rating.created_at.to_date - first_rating.created_at.to_date).to_i
        (0..interval).each { |i| 
          if (i >= ignore_below and ((index + i) < output.length))
            output[index + i][1] += 1
          end
        }
        # Skip over days that have already been counted
        ignore_below = index + interval
      }
    }
    
    total_memories = @course.components.count

    output.each do |x|
      if total_memories == 0
        x[1] = 100
      else   
        x[1] = Float(x[1]) / total_memories * 100.0
      end
    end

    output_json = { :course_achieved_stats => [output] }
    respond_to do |format|
      format.json { render :json => output_json.to_json }
    end
  end

  def student_status
    @course = Course.find(params[:id])
    @lessons = @course.lessons.includes(:lesson_statuses)
    @students_selected = "selected"
  end

  private

    def authorized_user
      if current_user.nil? or (current_user.perm != "admin" and current_user.perm != "creator")
        redirect_to root_path
      end
    end

    def authorized_teacher
      @course = Course.find(params[:id])
      if current_user.nil? or (current_user.perm != "admin" and !current_user.teacher?(@course))
        redirect_to root_path
      end
    end
    
    def choose_layout
      if [ 'student_status', 'edit' ].include? action_name
        'teacher'
      else
        'application'
      end
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_course.html.erb
<li>
<%= render :partial => 'courses/enrollment_button', :locals => {:course => course}%>
<h3><%= link_to course.name, course %></h3>
<div class="markdown">
<p><%= course.description %></p>
</div>
</li>

app/views/courses/_enroll.html.erb
<%= form_for current_user.enrollments.
  build(:course_id => @course.id) do |f| %>
    <div><%= f.hidden_field :course_id %></div>
    <div class = "actions"><%= f.submit "Enroll" %></div>
<% end %>

app/views/courses/_make_teacher.html.erb
<%= form_for(user.enrollments.find_by_course_id(course)) do |f| %>
  <div class = "field">
    <%= f.hidden_field :role, :value => "teacher" %>
  </div>
 <div class="actions">
   <%= f.submit "Make teacher" %>
 </div>
<% end %>

app/views/courses/_remove_self_as_teacher.html.erb
<%= form_for(user.enrollments.find_by_course_id(course)) do |f| %>
  <div class = "field">
    <%= f.hidden_field :role, :value => "student" %>
  </div>
 <div class="actions">
   <%= f.submit "Remove as teacher" %>
 </div>
<% end %>

app/views/courses/_stats.html.erb
<h3>Review activity (last 4 weeks)</h3>
<div class="chart" id="stat-chart" style="width:324px;height:200px"></div>
<h3>Course mastery</h3>
<div class="chart" id="achievement-chart" style="width:324px;height:200px"></div>
<div id="stats-course-id" class="hidden"><%= @course.id %></div>

app/views/courses/_student.html.erb
<li><%=link_to display_name(user), user %>
<% if current_user.can_edit?(@course) %>
  <div id= "add_teacher_form" class = "inline-button">
    <%= render :partial => 'courses/make_teacher', :locals => { :course => @course, :user => user  } %>
  </div>
<% end %>
</li>

app/views/courses/_teacher.html.erb
<li><%=link_to display_name(user), user %>
<% if (current_user.can_edit?(@course) && ( (current_user == user) || (current_user.perm == "admin")))%>
  <div id= "remove_self_teacher_form">
    <%= render :partial => 'remove_self_as_teacher', :locals => { :course => @course, :user => user  } %>
</div>
<% end %>
</li>

app/views/courses/_unenroll.html.erb
<%= form_for current_user.enrollments.find_by_course_id(@course),
              :html => { :method => :delete } do |f| %>
    <div class = "actions"><%= f.submit "Unenroll" %></div>
<% end %>

app/views/courses/index.html.erb
<% breadcrumb :courses %>
<ul id="courses">
  <%= render @courses %> 
</ul>

<% auth_user = current_user %>
<% if not auth_user.perm == "learner" %>
  <%= link_to "New Course", new_course_path %>
<% end %>

app/views/courses/new.html.erb
<% breadcrumb :new_course %>

<h1>Create a course</h1>

<%= render 'form' %>

app/views/courses/show.html.erb
<% breadcrumb :course, @course %>

  <% if current_user.student?(@course) %>

  <div id="course-wrap">
  <div id="course-content">
    <div id="exercises" class="course-section">
      <h2> Exercises </h2>
      <p>
      <% memories_due = current_user.memories_due_with_quiz(@course).count %>
      <% if memories_due == 0 %>
        Complete a lesson to unlock more exercises.
      <% else %>
        <div class="due-count">
        <div class="quizbutton round study-button">
          <%= link_to "Study now!", course_study_index_path(@course.id) %>
        </div>
          <%= pluralize(memories_due, "concept") %> to review</div>
      <% end %>
      </p>
    </div>


    <div id="lessons" class="course-section">
      <h2>Lessons</h2>
      <%if @lessons.empty? %>
        Course has no lessons.
      <% else %>
        <table>
          <% @lessons.each_with_index do |lesson, i| %>
            <% lesson_status = @lesson_statuses[i] %>
            <tr> 
              <td><span class="lesson-number"><%= i+1 %></span></td>
              <td class="completion">
                <% if lesson_status.completed %>
                  <div class="progress-wrap">
                    <div class="progress-value" style="background: #0a0; width: 100%;"></div></div>
                <% elsif lesson_status.started? %>
                  <% events = lesson.events.map{|e| e.id} %>
                  <% latest_event = lesson_status.event_id %>
                  <% progress = (events.index(latest_event)+1.0)/events.length*100 %>
                  <div class="progress-wrap">
                    <div class="progress-value" style="background: #0a0; width: <%= progress %>%;"></div></div>
                <% end %>
              </td>
              <td class="lesson-link"> <%= link_to lesson.name, [@course, lesson] %> </td>
              <td class="last-viewed">
                <% if lesson_status.event_id == -1 %>
                  not yet started
                <% else %>
                  viewed <%= time_ago_in_words(lesson_status.updated_at) %> ago
                <% end %>
              </td>
            </tr>
          <% end %>
        </table>
      <% end %>
    </div>
    <div id="components" class="course-section">
      <% if @components.empty? %>
      <% else %>
        <h2>Concepts</h2>
        <p>Start typing to look up a question<br />
        <div id="course_id" class="hidden"><%= @course.id %></div>
        <input type="text" id="course_components" size="30" /><br />
        <a href="#" id="component_help_link" class="quizbutton round">Learn more</a>
        or
        <%= link_to "see all concepts", course_memories_path(@course) %>
        </p>
      <% end %>
    </div>
  </div>
  <div id="stats-sidebar">
    <%= render :partial => 'stats' %>
  </div>

    <% content_for :javascript do %>
      <%= javascript_include_tag "jquery.flot.js" %>
      <%= javascript_include_tag "Stats" %>
    <% end %>
  <% else %>
  <div id="course-content">
    <h1><%= @course.name %></h1>

    <p class = markdown><%= @course.description %></p>
    <%= render :partial => 'users/enroll', :locals => { :course => @course } %>
  </div>
</div>

  <% end %>

app/views/courses/show_users.html.erb
<h1><%= @title %></h1>
<% unless @teachers.empty? %>
  <h2>Teachers</h2>
  <ul class = "users">
    <%= render :partial => "teacher", :collection => @teachers , :as => :user, :locals => {:course => @course, :user => @user } %>
  </ul>
<% end %>
<% unless @students.empty? %>
  <h2>Students</h2>
  <ul class = "users">
    <%= render :partial => "student", :collection => @students, :as => :user , :locals => { :course => @course, :user => @user }%>
  </ul>
  <%= will_paginate @students %>
<% end %>

app/views/courses/student_status.html.erb
<% breadcrumb :student_status, @course %>
<div id="student-status"> 
  <table>
    <tr>
      <td class="unused student-column"></td>
      <% @lessons.each { |lesson| %>
        <td class="label"><%= link_to lesson.name,edit_course_lesson_path(@course, lesson) %></td>
      <% } %>
    </tr>
    <% @course.student_enrollments.each { |enrollment| %>
      <% student = enrollment.user %>
      <tr>
        <td class="student-column">
          <%= link_to display_name(student), student %><br />
          (<%= (enrollment.course_completion*100).round %>%)
        </td>

        <% student.lesson_statuses.each { |lesson_status| %>
          <% lesson_status.completed? ? status="good" : lesson_status.event_id == -1 ? status="unviewed" : status="due" %> 
          <td class="<%= status %>"></td>
        <% } %>
      </tr>
    <% } %>
  </table>
</div>

app/views/courses/study.html.erb
<h1><%= @course.name %></h1>
<div id="study_area" class="round">
  <% if @step %>
    <div id="study_item">
        <%= @step.text %>
    </div>
    <div>
      \( \rightarrow \) was due <%= time_ago_in_words(@memory.due) %> ago.
    </div>
  <% else %>
    Nothing due right now.
  <% end %>
</div>